# These are supported funding model platforms
# You can uncomment and fill in the ones you want to use

# github: [username]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# lfx_crowdfunding: project-name
# polar: username
# buy_me_a_coffee: username
# custom: ["https://example.com/donate"]
