blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/rpr-development/flask_rpr_oauth#readme
    about: Check out the documentation before opening an issue
  - name: 💬 Discussions
    url: https://github.com/rpr-development/flask_rpr_oauth/discussions
    about: Ask questions and discuss ideas
